spring.application.name=deliverypersonapp
spring.kafka.bootstrap-servers=172.29.118.7:9092

# Producer config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer